### ISSUE TITLE
我希望您能将 Swifter.Json 作为默认 JSON 工具

### ISSUE THREAD

**Issue by Dogwei** [fanliang11/surging#301]
您好：

https://github.com/Dogwei/Swifter.Json 这个我们团队开发的 Swifer.Json 开源工具。

它有 扩展性强，性能高，小分配等优点；它还支持更多的 .Net 版本。
我们已经做了大量的测试和线上项目确保它的稳定性。

如果您愿意的话，我会帮助这个项目开发 JSON 模块，并帮助维护这个项目。

并且我注意到，您有打算使用 MessagePack 和 ProtoBuffer 作为数据格式；

这里我可以说 MessagePack 和 ProtoBuffer 就是就是 Swifter 接下来的要做的事；

Swifter 可以做到统一的配置和使用方式，并且降低切换的门槛。

😃!!!

附：性能测试结果图和优势对比图

![benckmark_for_framework_4 7 1](https://user-images.githubusercontent.com/14845492/58229842-51429e00-7d65-11e9-9d9c-fa4b75c1d5a6.png)

![Features](https://user-images.githubusercontent.com/14845492/58229867-5a336f80-7d65-11e9-94d2-46a9952893df.png)

**Comment by Andy-Yin** [comment]
专业！

**Comment by lonelygo** [comment]
这个必须点赞

**Comment by xiaobei930** [comment]
邮件已经收到,正在处理,请等待.
