### ISSUE TITLE
Surging.Core.CPlatform.Runtime.Client.Implementation.RemoteInvokeService  在创建和使用transportClient 之后没有释放 transportClient ，是否会造成内存泄漏呢

### ISSUE THREAD

**Issue by karqical2016** [fanliang11/surging#396]
Surging.Core.CPlatform.Runtime.Client.Implementation.RemoteInvokeService  在创建和使用transportClient 之后没有释放 transportClient ，是会造成内存泄漏

**Comment by fanliang11** [comment]
surging 使用的是RPC长连接，为什么要关闭？一个连接占用内存也就8k,一万台服务连接也就80mb左右，这点内存难道不能接受吗？

**Comment by karqical2016** [comment]
下面是在使用过程中发现的大对象记录：

0:000> !do 000001cd19001058
Name:        System.Byte[]
MethodTable: 00007fff98156dc0
EEClass:     00007fff97816d88
Size:        16777240(0x1000018) bytes
Array:       Rank 1, Number of elements 16777216, Type Byte (Print Array)
Content:     ................................................................................................................................
Fields:
None

0:000> !gcroot 000001c83b7d1058
Thread 53610:
    00000030b72be400 00007ffb6d8094c7 DotNetty.Transport.Libuv.LoopExecutor.StartLoop()
        rbp+10: 00000030b72be4b0
            ->  000001c816e12738 DotNetty.Transport.Libuv.DispatcherEventLoop
            ->  000001c816e197f8 DotNetty.Transport.Libuv.TcpServerChannel+TcpServerChannelUnsafe
            ->  000001c816e17d00 DotNetty.Transport.Libuv.TcpServerChannel
            ->  000001c816e19878 DotNetty.Transport.Channels.DefaultChannelPipeline
            ->  000001c816e1d378 DotNetty.Transport.Channels.DefaultChannelPipeline+HeadContext
            ->  000001c816e14ed0 DotNetty.Transport.Channels.DefaultChannelHandlerContext
            ->  000001c816e14a78 DotNetty.Transport.Bootstrapping.ServerBootstrap+ServerBootstrapAcceptor
            ->  000001c816e179a8 DotNetty.Transport.Channels.ActionChannelInitializer`1[[DotNetty.Transport.Channels.IChannel, DotNetty.Transport]]
            ->  000001c816e178c8 System.Action`1[[DotNetty.Transport.Channels.IChannel, DotNetty.Transport]]
            ->  000001c816e0a988 Surging.Core.DotNetty.DotNettyServerMessageListener
            ->  000001c816e1ebb8 Surging.Core.CPlatform.Transport.ReceivedDelegate
            ->  000001c816e0ab28 Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceHost
            ->  000001c816e08aa8 Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceExecutor
            ->  000001c81658fcc8 Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceEntryLocate
            ->  000001c815a922e0 Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceEntryManager
            ->  000001c815eceaa8 Surging.Core.CPlatform.Runtime.Server.ServiceEntry[]
            ->  000001c815ac91c8 Surging.Core.CPlatform.Runtime.Server.ServiceEntry
            ->  000001c815ac9210 System.Func`3[[System.String, System.Private.CoreLib],[System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib],[System.Threading.Tasks.Task`1[[System.Object, System.Private.CoreLib]], System.Private.CoreLib]]
            ->  000001c815ac7878 Surging.Core.CPlatform.Runtime.Server.Implementation.ServiceDiscovery.Implementation.ClrServiceEntryFactory+<>c__DisplayClass5_0
            ->  000001c815a904b8 Surging.Core.CPlatform.Runtime.Server.Implementation.ServiceDiscovery.Implementation.ClrServiceEntryFactory
            ->  000001c815a7ffe0 Surging.Core.CPlatform.CPlatformContainer
            ->  000001c81591dd18 Autofac.Core.Container
            ->  000001c81591e358 Autofac.Core.Lifetime.LifetimeScope
            ->  000001c81591e3d8 System.Collections.Concurrent.ConcurrentDictionary`2[[System.Guid, System.Private.CoreLib],[System.Object, System.Private.CoreLib]]
            ->  000001c816596330 System.Collections.Concurrent.ConcurrentDictionary`2+Tables[[System.Guid, System.Private.CoreLib],[System.Object, System.Private.CoreLib]]
            ->  000001c816593a10 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Guid, System.Private.CoreLib],[System.Object, System.Private.CoreLib]][]
            ->  000001c816f91038 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Guid, System.Private.CoreLib],[System.Object, System.Private.CoreLib]]
            ->  000001c816f8f3a0 Surging.Core.CPlatform.Support.Implementation.BreakeRemoteInvokeService
            ->  000001c8165b3b28 Surging.Core.CPlatform.Runtime.Client.Implementation.RemoteInvokeService
            ->  000001c81659a218 Surging.Core.DotNetty.DotNettyTransportClientFactory
            ->  000001c81659b418 System.Collections.Concurrent.ConcurrentDictionary`2[[System.Net.EndPoint, System.Net.Primitives],[System.Lazy`1[[System.Threading.Tasks.Task`1[[Surging.Core.CPlatform.Transport.ITransportClient, Surging.Core.CPlatform]], System.Private.CoreLib]], System.Private.CoreLib]]
            ->  000001c81659b610 System.Collections.Concurrent.ConcurrentDictionary`2+Tables[[System.Net.EndPoint, System.Net.Primitives],[System.Lazy`1[[System.Threading.Tasks.Task`1[[Surging.Core.CPlatform.Transport.ITransportClient, Surging.Core.CPlatform]], System.Private.CoreLib]], System.Private.CoreLib]]
            ->  000001c81659b500 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Net.EndPoint, System.Net.Primitives],[System.Lazy`1[[System.Threading.Tasks.Task`1[[Surging.Core.CPlatform.Transport.ITransportClient, Surging.Core.CPlatform]], System.Private.CoreLib]], System.Private.CoreLib]][]
            ->  000001c816f91b40 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Net.EndPoint, System.Net.Primitives],[System.Lazy`1[[System.Threading.Tasks.Task`1[[Surging.Core.CPlatform.Transport.ITransportClient, Surging.Core.CPlatform]], System.Private.CoreLib]], System.Private.CoreLib]]
            ->  000001c816f91b18 System.Lazy`1[[System.Threading.Tasks.Task`1[[Surging.Core.CPlatform.Transport.ITransportClient, Surging.Core.CPlatform]], System.Private.CoreLib]]
            ->  000001c816f93aa8 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Surging.Core.CPlatform.Transport.ITransportClient, Surging.Core.CPlatform],[Surging.Core.DotNetty.DotNettyTransportClientFactory+<>c__DisplayClass12_0+<<CreateClientAsync>b__1>d, Surging.Core.DotNetty]]
            ->  000001c816f95668 Surging.Core.CPlatform.Transport.Implementation.TransportClient
            ->  000001c816f955c8 Surging.Core.DotNetty.DotNettyMessageClientSender
            ->  000001c816f91b70 DotNetty.Transport.Channels.Sockets.TcpSocketChannel
            ->  000001c816f91f70 DotNetty.Transport.Channels.Sockets.TcpSocketChannel+TcpSocketChannelUnsafe
            ->  000001c8170cbb98 DotNetty.Transport.Channels.AdaptiveRecvByteBufAllocator+HandleImpl
            ->  000001c816f920c8 DotNetty.Transport.Channels.Sockets.TcpSocketChannel+TcpSocketChannelConfig
            ->  000001c8165a1a60 DotNetty.Buffers.PooledByteBufferAllocator
            ->  000001c8165a1af8 DotNetty.Buffers.PoolArena`1[[System.Byte[], System.Private.CoreLib]][]
            ->  000001c8165a8ea8 DotNetty.Buffers.HeapArena
            ->  000001c8165a9b88 DotNetty.Buffers.PoolSubpage`1[[System.Byte[], System.Private.CoreLib]][]
            ->  000001c8165a9c18 DotNetty.Buffers.PoolSubpage`1[[System.Byte[], System.Private.CoreLib]]
            ->  000001c817414e00 DotNetty.Buffers.PoolSubpage`1[[System.Byte[], System.Private.CoreLib]]
            ->  000001c81740ed40 DotNetty.Buffers.PoolChunk`1[[System.Byte[], System.Private.CoreLib]]
            ->  000001c83b7d1058 System.Byte[]

Found 1 unique roots (run '!gcroot -all' to see all roots).


这个部分 的方法表中占用的字节数比较大 。是从Dump文件中反映出来的，类似的方法表很多。

Surging 中RPC 长链接 的实现思路是下面的一种吗，或者这个长链接大致逻辑是什么呢

（1）对于每一次rpc请求，都单独建立一个tcp连接，请求完成之后关闭连接，每一个请求都需要独占一个tcp连接
（2）类似于（1）中实现，只不过对tcp连接做了缓存，类似于连接池的方案，每一次rpc请求都需要独占连接
（3）只建立一个连接，请求都共享这个连接，通过一些请求id来标示返回的数据应该属于哪一个请求。

**Comment by fanliang11** [comment]
https://github.com/Azure/DotNetty/issues/344
这是dotnetty的全局缓冲池默认初始化占用16MB，和transportClient无关，请自己学习或者购买服务，谢谢，社区版本只接受PR和BUG 提问

**Comment by karqical2016** [comment]
非常感谢，我已经明白如何处理，是DOTNETTY 初始化时做的坏味道

**Comment by karqical2016** [comment]
购买服务 怎么个价格范围，具体详情

**Comment by fanliang11** [comment]
童叟无欺价企业版28000，不还价。

**Comment by karqical2016** [comment]
有没有再详细的说明包含服务期限和内容范围。如果可以，能否发送份邮件 karqical@qq.com
