### ISSUE TITLE
单服务热加载问题

### ISSUE THREAD

**Issue by lipengfei12334** [fanliang11/surging#400]
在k8s中 发布单个服务 如何不重启网关 和整个服务体系 让服务自动加载完成热部署

**Comment by fanliang11** [comment]
服务引擎有consul 和 zookeeper 两种注册中心，前者是心跳更新服务路由到本地，后者是通过watcher 机制更新，而请求过的服务才会触发心跳， 心跳也会间隔一段时间进行同步更新到本地。你可以通过配置文件配置全量心跳更新或者修改间隔时间，这些配置会影响单机的注册中心性能，你需要进行配置或者部署多个注册中心

**Comment by lipengfei12334** [comment]
"Consul": {
    "ConnectionString": "${Register_Conn}|192.168.11.148:32657", // "192.168.11.148:32657",
    "SessionTimeout": "${Register_SessionTimeout}|50",
    "RoutePath": "${Register_RoutePath}",
    "LockDelay": 600, //����600��
    "ReloadOnChange": true,
    "EnableChildrenMonitor": false
  },

**Comment by lipengfei12334** [comment]
这是目前配置的 单服务器热加载无法处理

**Comment by lipengfei12334** [comment]
公司目前 已在生产环境上线了surging架构的微服务  目前想迁移到k8s中  本地测试已完成部署  现在就查热加载的问题了

**Comment by fanliang11** [comment]
热加载，创建动态代理有点问题，暂时还没找到解决方案
