### ISSUE TITLE
k8s中单服务重发之后 提示如下

### ISSUE THREAD

**Issue by lipengfei12334** [fanliang11/surging#403]
warn: Surging.Core.CPlatform.Runtime.Client.Address.Resolvers.Implementation.DefaultAddressResolver[0]
      根据服务id：Dora.Hosts.SRM.IApplication.Product.IProductInfoHostService.GetProductTypeToCascader_id，找不到可用的地址。
warn: Surging.Core.CPlatform.Runtime.Client.Address.Resolvers.Implementation.DefaultAddressResolver[0]
      根据服务id：Dora.Hosts.SRM.IApplication.Product.IProductInfoHostService.GetProductTypeToCascader_id，找不到可用的地址。

页面无数据

**Comment by fanliang11** [comment]
社区版不支持技术服务。

**Comment by lipengfei12334** [comment]
那个版本支持技术服务？

**Comment by fanliang11** [comment]
为了surging发展，请购买企业服务

**Comment by lipengfei12334** [comment]
有连接地址吗？

**Comment by fanliang11** [comment]
surging 已经服务于10多家企业，后面会持续SurgingVista上更新， 协议上有所改变，未经授权不能用于商业用途
