### ISSUE TITLE
NLog

### ISSUE THREAD

**Issue by TeslaHan** [fanliang11/surging#414]
你好，使用UseNLog，这个模块，然后加载到对应的服务中，日志不能记录
![image](https://user-images.githubusercontent.com/21988281/122888876-d8afd080-d374-11eb-9e11-ed0ebdd23aed.png)

![image](https://user-images.githubusercontent.com/21988281/122889042-0432bb00-d375-11eb-9386-ddb9b9ded56b.png)

**Comment by fanliang11** [comment]
谢谢关注社区版surging, UseNLog配置已过时，可以通过添加引用和基于Rootpath扫描加载Surging.Core.Nlog引擎组件。如果是多种类型的日志组件，请基于surgingsetting 文件配置using 配置节，把NLogModule添加进去
```C#
    "Packages": [
      {
        "TypeName": "EnginePartModule",
        "Using": "${UseEngineParts}|ServiceProxyModule;ProtokollwandlerModule;DotNettyModule;NLogModule;ConsulModule;MessagePackModule;WSProtocolModule;MqttProtocolModule;EventBusRabbitMQModule;CachingModule;KestrelHttpModule;SwaggerModule;ApiGeteWayModule;SkywalkingModule;KestrelNLogModule;GrpcModule;ApolloModule;LiveStreamModule;"
      }
    ]
'''

**Comment by TeslaHan** [comment]
> 谢谢关注社区版surging, UseNLog配置已过时，可以通过添加引用和基于Rootpath扫描加载Surging.Core.Nlog引擎组件。如果是多种类型的日志组件，请基于surgingsetting 文件配置using 配置节，把NLogModule添加进去
> 
> ```cs
>     "Packages": [
>       {
>         "TypeName": "EnginePartModule",
>         "Using": "${UseEngineParts}|ServiceProxyModule;ProtokollwandlerModule;DotNettyModule;NLogModule;ConsulModule;MessagePackModule;WSProtocolModule;MqttProtocolModule;EventBusRabbitMQModule;CachingModule;KestrelHttpModule;SwaggerModule;ApiGeteWayModule;SkywalkingModule;KestrelNLogModule;GrpcModule;ApolloModule;LiveStreamModule;"
>       }
>     ]
> '''
> ```

谢谢，你能抽时间回复。
我这里也通过setting文件配置using配置节，启动的时候，也能加载，但，还是不能打印日志，也通过引用的方式把nlog引入进来，但服务里面还是不能打印日志，麻烦
![image](https://user-images.githubusercontent.com/21988281/123031447-e158e300-d416-11eb-8610-b3d461bcd06f.png)
![image](https://user-images.githubusercontent.com/21988281/123031500-f170c280-d416-11eb-8299-b9fe30a3fc40.png)

**Comment by fanliang11** [comment]
你的using 里有SerilogModule ，这样会造成日志组件冲突，还有需要注意的是，如果你引用了
Surging.Core.KestrelHttpServer 组件，就需要附件Surging.Core.Kestrel.Nlog

**Comment by TeslaHan** [comment]
> 你的using 里有SerilogModule ，这样会造成日志组件冲突，还有需要注意的是，如果你引用了
> Surging.Core.KestrelHttpServer 组件，就需要附加引用Surging.Core.Kestrel.Nlog， 还需要在配置节using中添加KestrelNLogModule

你好，我去掉SerilogModule 模块，谢谢提醒，使用KestrelHttpServer,需要附件ketrel.Nlog模块。现在配置如下
![image](https://user-images.githubusercontent.com/21988281/123047719-36552300-d430-11eb-9693-e616bc3bcafb.png)
日志在服务中依旧无法打印
![image](https://user-images.githubusercontent.com/21988281/123048338-df9c1900-d430-11eb-94fb-ac2a1cb25890.png)

**Comment by fanliang11** [comment]
如果还有问题，我就不知道了，我这里没有问题，代码是从github下载的，几十家企业用户没有反应日志问题
![图片](https://user-images.githubusercontent.com/17928535/123059745-a8336980-d43c-11eb-9a21-b7ff8e754f7b.png)
![图片](https://user-images.githubusercontent.com/17928535/123059983-e761ba80-d43c-11eb-8f78-59837f966eef.png)

**Comment by TeslaHan** [comment]
谢谢！已查找到未引用Protocol.WS服务
