### ISSUE TITLE
开源邪教NCC介绍

### ISSUE THREAD

**Issue by tonyqus** [fanliang11/surging#418]
[新瓜又来了！DotNetCore.NPOI的前世今生](https://zhuanlan.zhihu.com/p/392670444)

[起底开源邪教NCC](https://zhuanlan.zhihu.com/p/392900974)

**Comment by fanliang11** [comment]
互相尊重，互相团结一起建设.NET开源社区，为社区贡献自己的力量，surging 是和平退出NCC，本意是建立起 微服务低代码平台生态，请大家不要胡乱猜测

**Comment by tonyqus** [comment]
互相尊重没错，但是对于邪教来说还是不用了，跟流氓不需要讲道理。我只是让他们知道山外有山人外有人的道理。.NET开源社区我混的时间比他们久多了，但我真的没有见过他们这样白嫖+霸凌这么厉害的，拿他们的话说“我们创造了开源历史”，我必须承认，你说的对！你们创造的是霸凌和白嫖的开源历史，全球首例~真的厉害。

另外我觉得surging有点可惜，其实加入不加入组织区别不大，只能说加入ncc是surging走的弯路。我能看出作者是个老好人，怎么和谐怎么来，其实我平时也很好相处，否则npoi口碑不会这么好。

最后，如果有可能的话，希望作者开始考虑重启这个项目，但很多白嫖和喷子的需求直接忽略就好，你的老好人是把双刃剑，如果你不这么好说话，不去理ncc的催促，也许你当初也不会暂停suring的维护，你觉得呢？

**Comment by fanliang11** [comment]
高调做事，低调做人，低调攒人品，无须管别人，努力走好自己的每一步，我也一直在维护surging ，而且surging让我赚到第一桶金，单捐赠就超过2万元，还有不少购买了企业版的。只是2019年因为过度劳累熬夜产生了心绞痛，年龄大了，需要保重身体，不只是为了我，还有为了我的家人。

**Comment by tonyqus** [comment]
嗯嗯，听上去混的不错哦。我的npoi捐款也有一些，但不多吧。那我大概知道surging的情况了，开源要赚钱不容易，创业更难，有需要帮忙介绍客户或者推广的话可以联系我。身体肯定是大头，是革命的本钱，我们这样的IT老人更要保重身体。

确实现在国内.NET圈有点乱，在大环境都是java和go的情况下，推广.net core和微软技术栈变得异常艰难，反正我观察下来过去几年的社区真的是快被消耗完了，ncc是一个原因，还有其他人，我就不点名了。反正看上去目前社区里的活跃分子都不太靠谱，哈哈哈，还是靠自己吧，共勉。
