### ISSUE TITLE
是否可以和现在比较流行的ABP开发框架做个无缝整合？

### ISSUE THREAD

**Issue by YahuiWong** [fanliang11/surging#55]
整合现有轮子，形成生态圈

**Comment by fanliang11** [comment]
谢谢你的关注，surging 和abp没有太多的交集。不会整合abp.

**Comment by jakcm** [comment]
可以直接在微服务里面调用ABP 的Application层，我已经集成进去了

**Comment by YahuiWong** [comment]
@jakcm 思路细节可以说下或者有Demo吗？

**Comment by KidoPlay** [comment]
abp目前拆成微服务还是有些痛苦的。
vNext现在应该在beta中。
稳定一些的时候，vNext整合进来应该是没有压力的。
